### ISSUE TITLE
Missing package Catmandu::Store::DBI

### ISSUE THREAD

**Issue by Kitania** [VlaamseKunstcollectie/Imagehub-Box#12]
When running Catmandu, it complained about a missing Catmandu::Store::DBI package. I installed this one manually on my virtual machine using the following command:
`plenv exec cpanm -n Catmandu::Store::DBI`

However, I didn't know how to add it properly into the ansible playbook, so I'll leave that to @netsensei.

**Comment by Hobbesball** [comment]
this was fixed in the Datahub-Factory by @netsensei in this commit: https://github.com/thedatahub/Datahub-Factory/commit/d93f4e01d691b069c57e08a2c5db3c99c034ec4a
