### ISSUE TITLE
changing cantaloupe config in the cantaloupe admin console fails

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub-Box#5]
When trying to change the cantaloupe config at http://cantaloupe.box/cantaloupe/admin changing anything and trying to save it results in a "Failed to save the configuration: Internal Server Error". I have no idea why this issue persists. This isn't too much of a blocker, since all the configuration can be manually changed in the opt/cantaloupe/cantalouper.properties file, but why the admin panel can't be used is beyond me.

**Comment by nvanderperren** [comment]
I also get the "Failed to save the configuration". But it gives me no reason why it failed. Maybe it's a problem in Cantaloupe?

Another strange thing is the warning under 'processors': "ImageMagickProcessor | Support for ImageMagick <7 will be removed in a future release. Please upgrade to version 7."

When I check the version with `convert -version`, it responds with: 

```
Version: ImageMagick 7.0.7-39 Q16 x86_64 2019-05-10 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): bzlib fontconfig freetype jbig jng jpeg lzma png tiff xml zlib
```

(this is the ImageMagick that was built from source with the imagemagick role - ...I think)

Unless this is a general (but confusing) warning.

**Comment by netsensei** [comment]
Seems like we're discussing two different issues here. So, let's create a separate one for the ImageMagick issue.

As far as the issue with the configuration is concerned:

* We should look for log files in the Tomcat folder since Cantaloupe is a War file.
* My first stop would be to look at the permissions of the configuration file. Maybe Cantaloupe tries to overwrite it but the tomcat user/group doesn't have the right permissions.

**Comment by nvanderperren** [comment]
It is indeed a right permissions issue. If I do `sudo chmod 777` on the `cantaloupe.properties`-file, I am able to save changes in the admin page. The original permissions are `644`.

- owner and group of cantalopue.properties is vagrant
- owner and group of the webapp folders of tomcat is tomcat8

As for now, I haven't found anything useful in the log files in `/var/logs/tomcat8/`. In the file `localhost_access_log.2019-05-14.txt` I saw that saving indeed returns a `500`.

I guess there are some things we can do:
- use same user for tomcat and cantaloupe
- create a group and add tomcat8 to this group (or something like that) and change write permissions
- just don't enable the admin page. we don't need it. everything can be changed by variables in `ansible/group_vars`

**Comment by netsensei** [comment]
I suggest going with the last option. 

> just don't enable the admin page. we don't need it. everything can be changed by variables in ansible/group_vars

Making the admin page operational creates a potential attack vector you now need to keep secure (password, ssl, etc.). So, if we don't need it, it's better to keep that complexity out of scope so we don't need to worry about it.

Moreover, writing to a configuration file on disk from a web interface comes with its own special flavour of security risks. You need some serious sanitisation of the input to avoid all kinds of potential injections that might compromise the server. Doing a `chmod 777` makes the file executable, and that's not what you want security-wise anyway.

**Comment by Hobbesball** [comment]
Thanks for the followup you two <3 disabled admin page in 6182fee8729e430faa005837f9919060d43e1f65 , closing this issue
