### ISSUE TITLE
exiftool missing in box to embed metadata in images?

### ISSUE THREAD

**Issue by nvanderperren** [VlaamseKunstcollectie/Imagehub-Box#6]
ResourceSpace needs ExifTool to embed metadata in images. It's missing now in the box.

<img width="434" alt="Schermafbeelding 2019-05-13 om 12 20 37" src="https://user-images.githubusercontent.com/17183054/57614476-a74f5e80-7579-11e9-84ac-b3759db4717a.png">

<img width="769" alt="Schermafbeelding 2019-05-13 om 12 20 50" src="https://user-images.githubusercontent.com/17183054/57614480-aa4a4f00-7579-11e9-8383-c9649b5539ea.png">

**Comment by Hobbesball** [comment]
Thanks for flagging this! I've added Exiftool to the list of system packages to be installed with the ansible playbook: 9891226564dfe6b1bdc5ebfa80357ec9adbb80c7
Rerunning the playbook or manually installing exiftool in your box should fix this issue.

**Comment by nvanderperren** [comment]
yay! I saw that imagemagick is also listed in the list of system packages. So maybe the imagemagick role is not necessary?

**Comment by Hobbesball** [comment]
Heh. This is what I get for adapting an existing box I didn't develop, and not reading the playbook properly before adding new roles. I'll delete the imagemagick role, I'm pretty sure the apt-get covers it. Thanks!
