### ISSUE TITLE
Create ResourceSpace database with Ansible

### ISSUE THREAD

**Issue by nvanderperren** [VlaamseKunstcollectie/Imagehub-Box#9]
I think it should be possible to create a Resourcespace database with Ansible without needing to SSH into the box. The solution is probably more or less the same as in #7. 

**Override the variables for the geerlingguy.mysql role**

`ansible/roles/external/geerlingguy.mysql/defaults/main.yml` has variables to create databases. 

```
# Databases.
mysql_databases: []
#   - name: example
#     collation: utf8_general_ci
#     encoding: utf8
#     replicate: 1
```

These should be overridden in a `mysql.yml` file in `ansible/group_vars/all`.

**PR**

I'm happy to try this. Just writing it down in an issue as a reminder.

**Comment by netsensei** [comment]
Assigning this issue to you. :-) Go for it and create a PR!
